### ISSUE TITLE
トップページを作成する

### ISSUE THREAD

**Issue by Toshimatu** [Toshimatu/TENAGE#2]
# TODO
- [ ] ロゴ
- [ ] ヘッダー部分
- [ ] メイン部分
- [ ] 使用する画像の選定
- [ ] ABOUT部分
- [ ] HOW TO USE部分
- [ ] REVIEWS部分
- [ ] POLICY部分
- [ ] スタートボタンの実装

**Comment by Toshimatu** [comment]
## ロゴ作成
![TENAGE_logo](https://user-images.githubusercontent.com/52368204/117082112-57788c00-ad7c-11eb-94b9-888d24c0bf17.png)

**Comment by Toshimatu** [comment]
- [ ] router-viewの導入
- [ ] Vuetifyの導入

**Comment by Toshimatu** [comment]
## 実施メモ
- ヘッダーについて、トップページはロゴと各種ボタン、トップページ以外はロゴのみ表示

**Comment by Toshimatu** [comment]
- [ ] 「TEN-AGEについて」を押下すると、該当箇所までスクロールする処理を書く
- [ ] 「使い方」を押下すると、該当箇所までスクロールする処理を書く
- [ ] 「フィードバック送信」を押下すると、お問い合わせフォームを開くようにする
- [ ] 「お知らせ」
